### ISSUE TITLE
Link with docker using travis to auto build and deploy all tags possible

### ISSUE THREAD

**Issue by AbdealiLoKo** [pywikibot-catfiles/docker-file-metadata#2]
Need to make some sort of auto-deployment so that as soon as a commit is pushed to master it will update the dockerhub image.

**Comment by drtrigon** [comment]
We need also to trigger a build and deployment of docker images on push (an successful travis build) of `file-metadata`. We should include a trigger into `.travis.yml` that triggers a `docker-file-metadata` travis build by travis API, see https://docs.travis-ci.com/user/triggering-builds.

**Comment by drtrigon** [comment]
Trigger build of `docker-file-metadata` in case of successful build of `file-metadata`:

DONE in https://github.com/pywikibot-catfiles/file-metadata/commit/25a0fa34b5fe98a4dbc400bcb442c08e86b7ee64 and https://github.com/pywikibot-catfiles/file-metadata/commit/6d1efc38ceae805841993e2520b5332051601925

Auto-deployment (push) of docker image to dockerhub not enabled yet (might cause a time issue on travis).

**Comment by drtrigon** [comment]
DONE, deployed to https://hub.docker.com/r/pywikibotcatfiles/file-metadata/tags/
