### ISSUE TITLE
UnicodeEncodeError in simple_bot.py

### ISSUE THREAD

**Issue by drtrigon** [pywikibot-catfiles/docker-file-metadata#7]
When running `drtrigon/catimages-gsoc` docker I get this error:

```
root@b8d44d47d61c:/# cd /opt/pywikibot-core; python pwb.py ../file-metadata/file_metadata/wikibot/simple_bot.py -cat:SVG_files -limit:5; cd /
Retrieving 5 pages from commons:commons.
libdc1394 error: Failed to initialize libdc1394
==== [[:File:"Single"Japanese castle Tenshu layout format.svg]] ====
Time taken to analyze: 2.129771sec

==== [[:File:9th Odia Wikipedia Anniversary.svg]] ====
Time taken to analyze: 1.411306sec

==== [[:File:A Dine Fork.svg]] ====
Time taken to analyze: 1.624925sec

==== [[:File:A conceptual drawing of a barge with very simple geometry.svg]] ====
Time taken to analyze: 1.643108sec

Traceback (most recent call last):
  File "pwb.py", line 270, in <module>
    if not main():
  File "pwb.py", line 264, in main
    run_python_file(filename, [filename] + args, argvu, file_package)
  File "pwb.py", line 109, in run_python_file
    main_mod.__dict__)
  File "../file-metadata/file_metadata/wikibot/simple_bot.py", line 240, in <module>
    main()
  File "../file-metadata/file_metadata/wikibot/simple_bot.py", line 235, in main
    print('\n'.join(log))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe7' in position 18: ordinal not in range(128)
<type 'exceptions.UnicodeEncodeError'>
CRITICAL: Waiting for 1 network thread(s) to finish. Press ctrl-c to abort
```

I cannot get rid of this it is clearly in https://github.com/pywikibot-catfiles/file-metadata/blob/master/file_metadata/wikibot/simple_bot.py#L196

**Comment by drtrigon** [comment]
Solved by `export PYTHONIOENCODING=UTF-8`, see:
- https://github.com/drtrigon/catimages-gsoc/blob/master/Dockerfile#L13
- https://github.com/drtrigon/catimages-gsoc/blob/master/.travis.yml#L12

as mentioned in: https://bots.wmflabs.org/~wm-bot/logs/%23gsoc-catimages/20160715.txt

**Comment by AbdealiLoKo** [comment]
Reopening as although that's a fix, the application should encode the strings to the correct encoding before printing.
Have you tired pywikibot.output() ?

**Comment by drtrigon** [comment]
`pywikibot.output()` works! Although the output seems to be arranged differently...

**Comment by drtrigon** [comment]
Opened https://github.com/pywikibot-catfiles/file-metadata/issues/55 as this should be solved there as mentioned.

Afterwards we can remove all `PYTHONIOENCODING=UTF-8` from Dockerfiles etc.
